FROM bref/php-81-fpm:latest

# 1. アプリコードをコピー
COPY src/ /var/task/

# 2. Composer インストール・最適化
RUN composer install --no-dev --optimize-autoloader

# 3. キャッシュ生成
RUN php artisan config:cache \
 && php artisan route:cache \
 && php artisan view:cache

# 4. Lambda ハンドラ設定
CMD ["public/index.php"]
