services:
  app:
    container_name: hourei-api-server_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hourei-api-server
      DB_USERNAME: me
      DB_PASSWORD: 54321


  web:
    container_name: hourei-api-server_nginx
    image: nginx:latest
    ports:
      - "8082:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    container_name: hourei-api-server_db
    image: mysql:8.0
    ports:
      - ":3306"
    environment:
      MYSQL_DATABASE: hourei-api-server
      MYSQL_USER: me
      MYSQL_PASSWORD: 54321
      MYSQL_ROOT_PASSWORD: 12345
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  frontend:
    container_name: hourei-api-server_frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    working_dir: /app
    volumes:
        - ./frontend:/app:delegated
        - node_modules:/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - app

volumes:
  mysql-volume: {}
  node_modules: {}
