services:
  api:
    container_name: hourei-api-server_api
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:8080"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

