services:
  api:
    container_name: hourei-api-server_api
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    env_file:
      - ./env/.env.production
    ports:
      - "8080:8080"
