name: Deploy Backend

on:
  push:
    branches:
      - main    # main ブランチにプッシュされたときのみ動かす

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: AWS 認証情報の設定
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-1

      - name: ECR へログイン
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker イメージをビルド・プッシュ
        env:
          ECR_REGISTRY:    ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY:  ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG:       ${{ github.sha }}
        run: |
          # Docker イメージのビルド
          docker build \
            --file docker/Dockerfile \
            --target production \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            .
          # ECR へプッシュ
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: App Runner デプロイをトリガー
        run: |
          aws apprunner start-deployment \
            --service-arn ${{ secrets.APP_RUNNER_SERVICE_ARN }}
