# .github/workflows/deploy-backend.yml
name: Deploy Backend
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        env:
          ECR_REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}    # e.g. hourei-api-server
          IMAGE_TAG:      latest
        run: |
          # フォルダをビルドコンテキストに指定
          docker build \
            --file src/docker/Dockerfile \
            --target production \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            src
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Trigger App Runner Deployment
        run: |
          aws apprunner start-deployment \
            --service-arn arn:aws:apprunner:ap-northeast-1:992382375868:service/hourei-api-server/e6797a89096b4705ad1681aa4822eab0
