name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: AWS 認証情報の設定
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-1

      - name: 依存パッケージのインストール
        working-directory: frontend
        run: npm ci

      - name: ビルド
        working-directory: frontend
        run: npm run build

      - name: S3 へ同期
        uses: aws-actions/s3-sync@v2
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_FRONTEND }}
          AWS_REGION:    ap-northeast-1
          SOURCE_DIR:    frontend/dist

      - name: CloudFront キャッシュ無効化
        uses: aws-actions/cloudfront-invalidate@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths:           '/*'
